//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNBManagement {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KNBManagement.Assets.Resources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   アプリ情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー登録はお済みですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlreadyRegisteredLabel {
            get {
                return ResourceManager.GetString("AlreadyRegisteredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KN&amp;B経営管理/コンサルティング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインに戻る に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackToLoginButton {
            get {
                return ResourceManager.GetString("BackToLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信中 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusyIndicatorCommunication {
            get {
                return ResourceManager.GetString("BusyIndicatorCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読込中 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusyIndicatorLoading {
            get {
                return ResourceManager.GetString("BusyIndicatorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アプリケーションの初期化中 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusyIndicatorLoadingUser {
            get {
                return ResourceManager.GetString("BusyIndicatorLoadingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン中 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusyIndicatorLoggingIn {
            get {
                return ResourceManager.GetString("BusyIndicatorLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザ情報を登録中 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusyIndicatorRegisteringUser {
            get {
                return ResourceManager.GetString("BusyIndicatorRegisteringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新中 ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusyIndicatorUpdating {
            get {
                return ResourceManager.GetString("BusyIndicatorUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経営管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InstallPageTitle {
            get {
                return ResourceManager.GetString("InstallPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   経理入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalInputPageTitle {
            get {
                return ResourceManager.GetString("JournalInputPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginWindowTitle {
            get {
                return ResourceManager.GetString("LoginWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogOffButton {
            get {
                return ResourceManager.GetString("LogOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセルの確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBoxCaptionCancel {
            get {
                return ResourceManager.GetString("MsgBoxCaptionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーメッセージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgBoxCaptionError {
            get {
                return ResourceManager.GetString("MsgBoxCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorCommunication {
            get {
                return ResourceManager.GetString("MsgErrorCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgErrorSubmit {
            get {
                return ResourceManager.GetString("MsgErrorSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー登録はお済みですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotRegisteredYetLabel {
            get {
                return ResourceManager.GetString("NotRegisteredYetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録はこちらから！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegisterNowButton {
            get {
                return ResourceManager.GetString("RegisterNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー登録に必要な項目を入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegistrationFormHeader {
            get {
                return ResourceManager.GetString("RegistrationFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegistrationWindowTitle {
            get {
                return ResourceManager.GetString("RegistrationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次回から自動的にログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RememberMeLabel {
            get {
                return ResourceManager.GetString("RememberMeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipPageTitle {
            get {
                return ResourceManager.GetString("SlipPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ようこそ {0} さん に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
