//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNBManagement.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KNBManageDataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KNBManageDataResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KNBManagement.Web.Resources.KNBManageDataResources", typeof(KNBManageDataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   業種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessTypeIDCol {
            get {
                return ResourceManager.GetString("BusinessTypeIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   業種コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessTypeIDLabel {
            get {
                return ResourceManager.GetString("BusinessTypeIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   業種名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessTypeNameCol {
            get {
                return ResourceManager.GetString("BusinessTypeNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   業種名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessTypeNameLabel {
            get {
                return ResourceManager.GetString("BusinessTypeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyIDCol {
            get {
                return ResourceManager.GetString("CompanyIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyIDLabel {
            get {
                return ResourceManager.GetString("CompanyIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyKeyCol {
            get {
                return ResourceManager.GetString("CompanyKeyCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyKeyLabel {
            get {
                return ResourceManager.GetString("CompanyKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyNameCol {
            get {
                return ResourceManager.GetString("CompanyNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyNameLabel {
            get {
                return ResourceManager.GetString("CompanyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貸方 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreditItemIDCol {
            get {
                return ResourceManager.GetString("CreditItemIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貸方項目コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreditItemIDLabel {
            get {
                return ResourceManager.GetString("CreditItemIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreditMoneyCol {
            get {
                return ResourceManager.GetString("CreditMoneyCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貸方金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreditMoneyLabel {
            get {
                return ResourceManager.GetString("CreditMoneyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   借方 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DebitItemIDCol {
            get {
                return ResourceManager.GetString("DebitItemIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   借方項目コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DebitItemIDLabel {
            get {
                return ResourceManager.GetString("DebitItemIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DebitMoneyCol {
            get {
                return ResourceManager.GetString("DebitMoneyCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   借方金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DebitMoneyLabel {
            get {
                return ResourceManager.GetString("DebitMoneyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   社員 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmployeeIDCol {
            get {
                return ResourceManager.GetString("EmployeeIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   社員コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmployeeIDLabel {
            get {
                return ResourceManager.GetString("EmployeeIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   社員名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmployeeNameCol {
            get {
                return ResourceManager.GetString("EmployeeNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   社員名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EmployeeNameLabel {
            get {
                return ResourceManager.GetString("EmployeeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalDetailIDCol {
            get {
                return ResourceManager.GetString("JournalDetailIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳詳細コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalDetailIDLabel {
            get {
                return ResourceManager.GetString("JournalDetailIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳Gr に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalGroupCol {
            get {
                return ResourceManager.GetString("JournalGroupCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalGroupLabel {
            get {
                return ResourceManager.GetString("JournalGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalIDCol {
            get {
                return ResourceManager.GetString("JournalIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalIDLabel {
            get {
                return ResourceManager.GetString("JournalIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalItemIDCol {
            get {
                return ResourceManager.GetString("JournalItemIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳項目ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalItemIDLabel {
            get {
                return ResourceManager.GetString("JournalItemIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalMoneyCol {
            get {
                return ResourceManager.GetString("JournalMoneyCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalMoneyLabel {
            get {
                return ResourceManager.GetString("JournalMoneyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalNameCol {
            get {
                return ResourceManager.GetString("JournalNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仕訳名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JournalNameLabel {
            get {
                return ResourceManager.GetString("JournalNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeywordLabel {
            get {
                return ResourceManager.GetString("KeywordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginIDCol {
            get {
                return ResourceManager.GetString("LoginIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginIDLabel {
            get {
                return ResourceManager.GetString("LoginIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasswordCol {
            get {
                return ResourceManager.GetString("PasswordCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   摘要 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemarksCol {
            get {
                return ResourceManager.GetString("RemarksCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   摘要 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemarksLabel {
            get {
                return ResourceManager.GetString("RemarksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipDetailIDCol {
            get {
                return ResourceManager.GetString("SlipDetailIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票詳細コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipDetailIDLabel {
            get {
                return ResourceManager.GetString("SlipDetailIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   順番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipDetailOrderCol {
            get {
                return ResourceManager.GetString("SlipDetailOrderCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   順番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipDetailOrderLabel {
            get {
                return ResourceManager.GetString("SlipDetailOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipIDCol {
            get {
                return ResourceManager.GetString("SlipIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipIDLabel {
            get {
                return ResourceManager.GetString("SlipIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票種別名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipNameCol {
            get {
                return ResourceManager.GetString("SlipNameCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票種別名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipNameLabel {
            get {
                return ResourceManager.GetString("SlipNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票種別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipTypeIDCol {
            get {
                return ResourceManager.GetString("SlipTypeIDCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   伝票種別コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SlipTypeIDLabel {
            get {
                return ResourceManager.GetString("SlipTypeIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TradingDateCol {
            get {
                return ResourceManager.GetString("TradingDateCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TradingDateLabel {
            get {
                return ResourceManager.GetString("TradingDateLabel", resourceCulture);
            }
        }
    }
}
