//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNBManagement.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KNBManagement.Web.Resources.ValidationErrorResources", typeof(ValidationErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The friendly name cannot be more than 255 characters long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationErrorBadFriendlyNameLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadFriendlyNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password must be at least 7 and at most 50 characters long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationErrorBadPasswordLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A password needs to contain at least one special character e.g. @ or # に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationErrorBadPasswordStrength {
            get {
                return ResourceManager.GetString("ValidationErrorBadPasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名の長さが不正です。４～２５５文字の間で入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationErrorBadUserNameLength {
            get {
                return ResourceManager.GetString("ValidationErrorBadUserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なEメールアドレスです。user@company.com のように入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なユーザー名です。英数字のみを入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationErrorInvalidUserName {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが一致しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationErrorPasswordConfirmationMismatch {
            get {
                return ResourceManager.GetString("ValidationErrorPasswordConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この項目は必須項目です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationErrorRequiredField {
            get {
                return ResourceManager.GetString("ValidationErrorRequiredField", resourceCulture);
            }
        }
    }
}
